### PR TITLE
Create zh_CN.po

### PR DESCRIPTION
**Pull request by cesaryuan**
Simplified Chinese translation by machine.

### CODE REVIEW

**Comment by hanna-kn** [comment]
Has the accuracy of the machine translation been verified. I'm willing to merge the pull request even if this is not the case, but until each translated text string has been verified in its proper context, the translation will not be included in any released version.

**Comment by cesaryuan** [comment]
> Has the accuracy of the machine translation been verified. I'm willing to merge the pull request even if this is not the case, but until each translated text string has been verified in its proper context, the translation will not be included in any released version.

I'm sorry I haven't checked it out yet, but I'll do it later when I have time. And I wonder if I can just replace the libqalculate.mo file under the locale folder to make it work.

**Comment by hanna-kn** [comment]
> And I wonder if I can just replace the libqalculate.mo file under the locale folder to make it work.

No. libqalculate.mo is the translation for libqalculate (mainly includes error messages, and titles, descriptions and names for functions, variables and units).

The _compiled_ qalculate-gtk translation file should be placed in the folder as qalculate-gtk.mo. The po file can be compiled from the source tree (add zh_CN to ALL_LINGUAS in configure.ac), or using `msgfmt -o qalculate-gtk.mo zh_CN.po` (or you can download it at https://send.firefox.com/download/6e906c260a3664d4/#AnA12HMKJ2tKrqmSToZvkA).

**Comment by cesaryuan** [comment]
@hanna-kn Thank you. I'll try to verify every translation.

**Pull request closed without merging**
